### ISSUE TITLE
Log capture issue - TypeError: expected str, bytes or os.PathLike object, not StringIO

### ISSUE THREAD

**Issue by ry-sny** [qase-tms/qase-python#159]
Config:
```
{
	"mode": "testops",
	"fallback": "report",
	"report": {
		"driver": "local",
		"connection": {
			"local": {
				"path": "./build/qase-report",
				"format": "json"
			}
		}
	},
	"testops": {
		"bulk": false,
		"api": {
			"token": "<TOKEN>",
			"host": "qase.io"
		},
		"defect": true,
		"project": "<PROJECT_CODE>",
		"chunk": 200
	},
	"framework": {
		"pytest": {
			"capture": {
				"logs": true,
				"http": true
			}
		}
	},
	"environment": "local"
}
```

Tests being ran:
```
import random
import time

import pytest


@pytest.mark.parametrize("number", [1, 2, 3, 4, 5])
def test_params(number):
    print("test")
    assert number % 3 != 0


def test_random_sleep():
    time.sleep(random.randrange(6))
    
```

Error:
```
[Qase] Sending a result to test run 64...

INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/Users/rsnyder/Code/mock-qase-repo/venv/lib/python3.11/site-packages/_pytest/main.py", line 269, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>                          ^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/Users/rsnyder/Code/mock-qase-repo/venv/lib/python3.11/site-packages/_pytest/main.py", line 323, in _main
INTERNALERROR>     config.hook.pytest_runtestloop(session=session)
INTERNALERROR>   File "/Users/rsnyder/Code/mock-qase-repo/venv/lib/python3.11/site-packages/pluggy/_hooks.py", line 501, in __call__
INTERNALERROR>     return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
INTERNALERROR>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/Users/rsnyder/Code/mock-qase-repo/venv/lib/python3.11/site-packages/pluggy/_manager.py", line 119, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/Users/rsnyder/Code/mock-qase-repo/venv/lib/python3.11/site-packages/pluggy/_callers.py", line 181, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>            ^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/Users/rsnyder/Code/mock-qase-repo/venv/lib/python3.11/site-packages/pluggy/_result.py", line 99, in get_result
INTERNALERROR>     raise exc.with_traceback(exc.__traceback__)
INTERNALERROR>   File "/Users/rsnyder/Code/mock-qase-repo/venv/lib/python3.11/site-packages/pluggy/_callers.py", line 102, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>           ^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/Users/rsnyder/Code/mock-qase-repo/venv/lib/python3.11/site-packages/_pytest/main.py", line 348, in pytest_runtestloop
INTERNALERROR>     item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
INTERNALERROR>   File "/Users/rsnyder/Code/mock-qase-repo/venv/lib/python3.11/site-packages/pluggy/_hooks.py", line 501, in __call__
INTERNALERROR>     return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
INTERNALERROR>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/Users/rsnyder/Code/mock-qase-repo/venv/lib/python3.11/site-packages/pluggy/_manager.py", line 119, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/Users/rsnyder/Code/mock-qase-repo/venv/lib/python3.11/site-packages/pluggy/_callers.py", line 155, in _multicall
INTERNALERROR>     teardown[0].send(outcome)
INTERNALERROR>   File "/Users/rsnyder/Code/mock-qase-repo/venv/lib/python3.11/site-packages/qaseio/pytest/plugin.py", line 116, in pytest_runtest_protocol
INTERNALERROR>     self.finish_pytest_item(item)
INTERNALERROR>   File "/Users/rsnyder/Code/mock-qase-repo/venv/lib/python3.11/site-packages/qaseio/pytest/plugin.py", line 171, in finish_pytest_item
INTERNALERROR>     self.reporter.add_result(self.runtime.result)
INTERNALERROR>   File "/Users/rsnyder/Code/mock-qase-repo/venv/lib/python3.11/site-packages/qaseio/commons/testops.py", line 374, in add_result
INTERNALERROR>     self._send_result(result)
INTERNALERROR>   File "/Users/rsnyder/Code/mock-qase-repo/venv/lib/python3.11/site-packages/qaseio/commons/testops.py", line 300, in _send_result
INTERNALERROR>     attached.extend(self._upload(attachment))
INTERNALERROR>                     ^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/Users/rsnyder/Code/mock-qase-repo/venv/lib/python3.11/site-packages/qaseio/commons/testops.py", line 247, in _upload
INTERNALERROR>     return api_attachments.upload_attachment(
INTERNALERROR>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/Users/rsnyder/Code/mock-qase-repo/venv/lib/python3.11/site-packages/pydantic/validate_call_decorator.py", line 58, in wrapper_function
INTERNALERROR>     return validate_call_wrapper(*args, **kwargs)
INTERNALERROR>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/Users/rsnyder/Code/mock-qase-repo/venv/lib/python3.11/site-packages/pydantic/_internal/_validate_call.py", line 81, in __call__
INTERNALERROR>     res = self.__pydantic_validator__.validate_python(pydantic_core.ArgsKwargs(args, kwargs))
INTERNALERROR>           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/Users/rsnyder/Code/mock-qase-repo/venv/lib/python3.11/site-packages/qaseio/api/attachments_api.py", line 945, in upload_attachment
INTERNALERROR>     _param = self._upload_attachment_serialize(
INTERNALERROR>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/Users/rsnyder/Code/mock-qase-repo/venv/lib/python3.11/site-packages/qaseio/api/attachments_api.py", line 1184, in _upload_attachment_serialize
INTERNALERROR>     return self.api_client.param_serialize(
INTERNALERROR>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/Users/rsnyder/Code/mock-qase-repo/venv/lib/python3.11/site-packages/qaseio/api_client.py", line 211, in param_serialize
INTERNALERROR>     post_params.extend(self.files_parameters(files))
INTERNALERROR>                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/Users/rsnyder/Code/mock-qase-repo/venv/lib/python3.11/site-packages/qaseio/api_client.py", line 521, in files_parameters
INTERNALERROR>     with open(n, 'rb') as f:
INTERNALERROR>          ^^^^^^^^^^^^^
INTERNALERROR> TypeError: expected str, bytes or os.PathLike object, not StringIO

```

Upon debugging I see that this error is being thrown while trying to read `stdout.txt`, any idea what's going on here? If I set capture logs to `false` this error goes away.

**Comment by NickVolynkin** [comment]
Resolved in #169
