### ISSUE TITLE
Test results are logged partially and test run don't complete

### ISSUE THREAD

**Issue by AFerster** [qase-tms/qase-python#235]
We are currently struggling with logging our tests using qase. The problem is that test run is logged in qase only partially and run stays in "In progress" status. 
Maybe it can be caused by a large quantity of tests (more than 1200), and the fact that the most of them are parametrized. 

currently we are using  qase-pytest==6.1.0b1, but we have tried other versions, even beta. 

We checked that test run is fully completed in pytest and Qase also states this in log:

```
[Qase][09:20:06][debug] Results for run 629 sent successfully
[Qase][09:20:06][debug] Completing run 629
[Qase][09:20:07][info] Run 629 was completed successfully
[Qase][09:20:07][debug] Run completed
[Qase][09:20:07][info] Overhead for Qase Report: 76974ms

```
we also make completion of qase test run obligatory by option - `--qase-testops-run-complete=true`

We thought that this command line option - `--qase-testops-batch-size` can somehow help us to resolve this problem, and send the full package of test results to the server. 
But it is not quiet clear, what this option does: readme file is not very helpful in this regard. We tried to change the default value (200), but have only got an error: 

```
`INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/usr/local/lib/python3.12/site-packages/_pytest/main.py", line 26[8](https://github.com/flowwow/qa_test/actions/runs/10185306602/job/28174598985#step:8:9), in wrap_session
INTERNALERROR>     config._do_configure()
INTERNALERROR>   File "/usr/local/lib/python3.12/site-packages/_pytest/config/__init__.py", line 1072, in _do_configure
INTERNALERROR>     self.hook.pytest_configure.call_historic(kwargs=dict(config=self))
INTERNALERROR>   File "/usr/local/lib/python3.12/site-packages/pluggy/_hooks.py", line 535, in call_historic
INTERNALERROR>     res = self._hookexec(self.name, self._hookimpls.copy(), kwargs, False)
INTERNALERROR>           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/usr/local/lib/python3.12/site-packages/pluggy/_manager.py", line 120, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/usr/local/lib/python3.12/site-packages/pluggy/_callers.py", line 13[9](https://github.com/flowwow/qa_test/actions/runs/10185306602/job/28174598985#step:8:10), in _multicall
INTERNALERROR>     raise exception.with_traceback(exception.__traceback__)
INTERNALERROR>   File "/usr/local/lib/python3.12/site-packages/pluggy/_callers.py", line [10](https://github.com/flowwow/qa_test/actions/runs/10185306602/job/28174598985#step:8:11)3, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>           ^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/usr/local/lib/python3.12/site-packages/qase/pytest/conftest.py", line 17, in pytest_configure
INTERNALERROR>     config_manager = setup_config_manager(config)
INTERNALERROR>                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/usr/local/lib/python3.12/site-packages/qase/pytest/conftest.py", line 109, in setup_config_manager
INTERNALERROR>     config_manager.config.testops.batch.set_size(config.option.__dict__[option])
INTERNALERROR>   File "/usr/local/lib/python3.12/site-packages/qase/commons/models/config/batch.py", line [11](https://github.com/flowwow/qa_test/actions/runs/10185306602/job/28174598985#step:8:12), in set_size
INTERNALERROR>     if size > 2000 or size == 0:
INTERNALERROR>        ^^^^^^^^^^^
INTERNALERROR> TypeError: '>' not supported between instances of 'str' and 'int'`

```
which was very unexpected, because we clearly passed int as argument.

Please, can you clarify us the purpose of this command line option `--qase-testops-batch-size`, and maybe suggest how to configure qase in a way, that we avoid problems with logging.

**Comment by gibiw** [comment]
@AFerster  thanks for noticing! Try to update qase-pytest to 6.1.0b2.
