### ISSUE TITLE
Invalid type for qs_testplan_id in pytest.ini

### ISSUE THREAD

**Issue by Nickolasll** [qase-tms/qase-python#49]
In examples for INI file parameters I see
```
qs_testplan_id (string):
                        default value for --qase-testplan
```

If I use `qs_testplan_id = 1` I got this error

```
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/usr/local/lib/python3.8/dist-packages/_pytest/main.py", line 264, in wrap_session
INTERNALERROR>     config._do_configure()
INTERNALERROR>   File "/usr/local/lib/python3.8/dist-packages/_pytest/config/__init__.py", line 981, in _do_configure
INTERNALERROR>     self.hook.pytest_configure.call_historic(kwargs=dict(config=self))
INTERNALERROR>   File "/usr/local/lib/python3.8/dist-packages/pluggy/_hooks.py", line 277, in call_historic
INTERNALERROR>     res = self._hookexec(self.name, self.get_hookimpls(), kwargs, False)
INTERNALERROR>   File "/usr/local/lib/python3.8/dist-packages/pluggy/_manager.py", line 80, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR>   File "/usr/local/lib/python3.8/dist-packages/pluggy/_callers.py", line 60, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/usr/local/lib/python3.8/dist-packages/pluggy/_result.py", line 60, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/usr/local/lib/python3.8/dist-packages/pluggy/_callers.py", line 39, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/usr/local/lib/python3.8/dist-packages/qaseio/pytest/conftest.py", line 84, in pytest_configure
INTERNALERROR>     QasePytestPluginSingleton.init(
INTERNALERROR>   File "/usr/local/lib/python3.8/dist-packages/qaseio/pytest/plugin.py", line 472, in init
INTERNALERROR>     QasePytestPluginSingleton._instance = QasePytestPlugin(**kwargs)
INTERNALERROR>   File "/usr/local/lib/python3.8/dist-packages/qaseio/pytest/plugin.py", line 143, in __init__
INTERNALERROR>     self.check_testrun()
INTERNALERROR>   File "/usr/local/lib/python3.8/dist-packages/qaseio/pytest/plugin.py", line 195, in check_testrun
INTERNALERROR>     test_plan = api_plans.get_plan(
INTERNALERROR>   File "/usr/local/lib/python3.8/dist-packages/qaseio/api/plans_api.py", line 637, in get_plan
INTERNALERROR>     return self.get_plan_endpoint.call_with_http_info(**kwargs)
INTERNALERROR>   File "/usr/local/lib/python3.8/dist-packages/qaseio/api_client.py", line 859, in call_with_http_info
INTERNALERROR>     self.__validate_inputs(kwargs)
INTERNALERROR>   File "/usr/local/lib/python3.8/dist-packages/qaseio/api_client.py", line 753, in __validate_inputs
INTERNALERROR>     fixed_val = validate_and_convert_types(
INTERNALERROR>   File "/usr/local/lib/python3.8/dist-packages/qaseio/model_utils.py", line 1583, in validate_and_convert_types
INTERNALERROR>     converted_instance = attempt_convert_item(
INTERNALERROR>   File "/usr/local/lib/python3.8/dist-packages/qaseio/model_utils.py", line 1458, in attempt_convert_item
INTERNALERROR>     raise get_type_error(input_value, path_to_item, valid_classes,
INTERNALERROR> qaseio.exceptions.ApiTypeError: Invalid type for variable 'id'. Required value type is int and passed type was str at ['id']

Process finished with exit code 3
```

It has id = '1' in debugger, but it expects id to be int type.

**Comment by n3r** [comment]
Fixed in #66. Will be released with the next update.

In qase-pytest-4.0.0 we have changed param name. Now it has the following name: `qs_plan_id`.
